version: "3.1"

# bash into container docker exec -it user sh

services:
  user:
    build:
      context: .
      dockerfile: ./services/user/Dockerfile
      target: builder
    container_name: user
    command: air
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    volumes:
      - "./services/user/:/app/services/user"
      - "./packages/:/app/packages"
    environment:
      MYSQL: root:rootPassword@tcp(mysql:3306)/sessions?parseTime=true

  party:
    build:
      context: .
      dockerfile: ./services/party/Dockerfile
      target: builder
    container_name: party
    command: air
    depends_on:
      - dynamodb-local
    ports:
      - "8082:8080"
    volumes:
      - "./services/party/:/app/services/party"
      - "./packages/:/app/packages"
    environment:
      DYNAMO_HOST: http://dynamodb-local
      DYNAMO_PORT: 8000

  typesense:
    image: typesense/typesense:0.23.0.rc27
    container_name: typesense
    entrypoint: sh -c "/opt/typesense-server --data-dir /data --api-key=local-typesense-api-key --enable-cors"
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./data/typesense:/data

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    volumes:
      - ./data/dynamodata:/data
    ports:
      - "8042:8000"

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword

  envoy:
    image: envoyproxy/envoy:v1.20-latest
    container_name: envoy
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    command:
      - -l debug
      - -c /etc/envoy/envoy.yaml
