version: "3.1"

# bash into container docker exec -it user sh

services:
  #typesense:
  #  container_name: typesense
  #  entrypoint: sh -c "/opt/typesense-server --data-dir /data --api-key=local-typesense-api-key --enable-cors"
  #  restart: on-failure
  #  ports:
  #    - "8108:8108"
  #  volumes:
  #    - ./data/typesense:/data

  scylla:
    container_name: scylla
    image: scylladb/scylla:latest
    command: --smp 2 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    ports:
      - "9042:9042"
    volumes:
      - ./_data/scylla1:/var/lib/scylla/data

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./_data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword

  nats:
    image: nats
    container_name: nats
    expose:
      - "4222"
    ports:
      - "8222:8222"
      - "4222:4222"