version: "3.1"

services:
  #user:
  #  build:
  #    context: .
  #    dockerfile: ./services/user/Dockerfile
  #    target: builder
  #  container_name: user
  #  depends_on:
  #    - mysql
  #  ports:
  #    - "8081:8080"
  #  command: sh -c "cd services/user && air"
  #  volumes:
  #    - "./services/user/:/app/services/user"
  #  environment:
  #    TOKEN_SECRET: 5c9bf5dadd251ed23fc9f921c7ef426324ecbc8857c9f856a6c1376d971254309cea2c4e78ccc03c32dee2b8ce62c383
  #    MYSQL: root:rootPassword@tcp(mysql:3306)/sessions?parseTime=true

  typesense:
    image: typesense/typesense:0.23.0.rc27
    container_name: typesense
    entrypoint: sh -c "/opt/typesense-server --data-dir /data --api-key=local-typesense-api-key --enable-cors"
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./data/typesense:/data

  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "7000:8000"
    volumes:
      - "./data/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword

  envoy:
    image: envoyproxy/envoy:v1.20-latest
    container_name: envoy
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    command:
      - -l debug
      - -c /etc/envoy/envoy.yaml
