// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: packages/comtypes/comtypes.proto

package comtypes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FriendRequestNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequesterId string `protobuf:"bytes,1,opt,name=requesterId,proto3" json:"requesterId,omitempty"`
	RequestedId string `protobuf:"bytes,2,opt,name=requestedId,proto3" json:"requestedId,omitempty"`
}

func (x *FriendRequestNotification) Reset() {
	*x = FriendRequestNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_comtypes_comtypes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendRequestNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestNotification) ProtoMessage() {}

func (x *FriendRequestNotification) ProtoReflect() protoreflect.Message {
	mi := &file_packages_comtypes_comtypes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestNotification.ProtoReflect.Descriptor instead.
func (*FriendRequestNotification) Descriptor() ([]byte, []int) {
	return file_packages_comtypes_comtypes_proto_rawDescGZIP(), []int{0}
}

func (x *FriendRequestNotification) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *FriendRequestNotification) GetRequestedId() string {
	if x != nil {
		return x.RequestedId
	}
	return ""
}

type PartyCreatedNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatorId string `protobuf:"bytes,1,opt,name=creatorId,proto3" json:"creatorId,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *PartyCreatedNotification) Reset() {
	*x = PartyCreatedNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_comtypes_comtypes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartyCreatedNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyCreatedNotification) ProtoMessage() {}

func (x *PartyCreatedNotification) ProtoReflect() protoreflect.Message {
	mi := &file_packages_comtypes_comtypes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyCreatedNotification.ProtoReflect.Descriptor instead.
func (*PartyCreatedNotification) Descriptor() ([]byte, []int) {
	return file_packages_comtypes_comtypes_proto_rawDescGZIP(), []int{1}
}

func (x *PartyCreatedNotification) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *PartyCreatedNotification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CommentedNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorId string `protobuf:"bytes,1,opt,name=authorId,proto3" json:"authorId,omitempty"`
	PartyId  string `protobuf:"bytes,2,opt,name=partyId,proto3" json:"partyId,omitempty"`
	Body     string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *CommentedNotification) Reset() {
	*x = CommentedNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packages_comtypes_comtypes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentedNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentedNotification) ProtoMessage() {}

func (x *CommentedNotification) ProtoReflect() protoreflect.Message {
	mi := &file_packages_comtypes_comtypes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentedNotification.ProtoReflect.Descriptor instead.
func (*CommentedNotification) Descriptor() ([]byte, []int) {
	return file_packages_comtypes_comtypes_proto_rawDescGZIP(), []int{2}
}

func (x *CommentedNotification) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CommentedNotification) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *CommentedNotification) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_packages_comtypes_comtypes_proto protoreflect.FileDescriptor

var file_packages_comtypes_comtypes_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x6d, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x5f, 0x0a, 0x19,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x49, 0x64, 0x22, 0x4e, 0x0a,
	0x18, 0x50, 0x61, 0x72, 0x74, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x61, 0x0a,
	0x15, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x72, 0x74, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x72, 0x74, 0x79, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a,
	0x6f, 0x6e, 0x61, 0x73, 0x68, 0x69, 0x6c, 0x74, 0x6c, 0x2f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6d,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_packages_comtypes_comtypes_proto_rawDescOnce sync.Once
	file_packages_comtypes_comtypes_proto_rawDescData = file_packages_comtypes_comtypes_proto_rawDesc
)

func file_packages_comtypes_comtypes_proto_rawDescGZIP() []byte {
	file_packages_comtypes_comtypes_proto_rawDescOnce.Do(func() {
		file_packages_comtypes_comtypes_proto_rawDescData = protoimpl.X.CompressGZIP(file_packages_comtypes_comtypes_proto_rawDescData)
	})
	return file_packages_comtypes_comtypes_proto_rawDescData
}

var file_packages_comtypes_comtypes_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_packages_comtypes_comtypes_proto_goTypes = []interface{}{
	(*FriendRequestNotification)(nil), // 0: comtypes.FriendRequestNotification
	(*PartyCreatedNotification)(nil),  // 1: comtypes.PartyCreatedNotification
	(*CommentedNotification)(nil),     // 2: comtypes.CommentedNotification
}
var file_packages_comtypes_comtypes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packages_comtypes_comtypes_proto_init() }
func file_packages_comtypes_comtypes_proto_init() {
	if File_packages_comtypes_comtypes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_packages_comtypes_comtypes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendRequestNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packages_comtypes_comtypes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartyCreatedNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packages_comtypes_comtypes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentedNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_packages_comtypes_comtypes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packages_comtypes_comtypes_proto_goTypes,
		DependencyIndexes: file_packages_comtypes_comtypes_proto_depIdxs,
		MessageInfos:      file_packages_comtypes_comtypes_proto_msgTypes,
	}.Build()
	File_packages_comtypes_comtypes_proto = out.File
	file_packages_comtypes_comtypes_proto_rawDesc = nil
	file_packages_comtypes_comtypes_proto_goTypes = nil
	file_packages_comtypes_comtypes_proto_depIdxs = nil
}
