basePath: /
definitions:
  comtypes.MessageRes:
    properties:
      message:
        type: string
    required:
    - message
    type: object
  datastruct.PublicParty:
    properties:
      creatorId:
        type: string
      id:
        description: PARTY#CreatorId
        type: string
      isPublic:
        type: boolean
      lat:
        type: number
      long:
        type: number
      title:
        type: string
      ttl:
        type: string
    type: object
  echo.HTTPError:
    properties:
      message: {}
    type: object
  handler.CreatePartyBody:
    properties:
      isPublic:
        type: boolean
      lat:
        type: number
      long:
        type: number
      title:
        type: string
    required:
    - lat
    - long
    - title
    type: object
  handler.UpdatePartyBody:
    properties:
      isPublic:
        type: boolean
      lat:
        type: number
      long:
        type: number
      title:
        type: string
    required:
    - lat
    - long
    - title
    type: object
host: localhost:8082
info:
  contact: {}
  description: This Microservice manages Party entities
  title: Party Microservice
  version: "1.0"
paths:
  /:
    post:
      consumes:
      - application/json
      description: Create a new Party in DB
      parameters:
      - description: The body to create a party
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/handler.CreatePartyBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/datastruct.PublicParty'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Create a party
      tags:
      - CRUD
  /{pId}:
    delete:
      consumes:
      - application/json
      description: Deletes a party from our db
      parameters:
      - description: Party Id
        in: path
        name: pId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comtypes.MessageRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Delete a party
      tags:
      - CRUD
    get:
      consumes:
      - application/json
      description: Get a Party by it's id
      parameters:
      - description: Party Id
        in: path
        name: pId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/datastruct.PublicParty'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Get party
      tags:
      - CRUD
    patch:
      consumes:
      - application/json
      description: Updates a party with the provided values
      parameters:
      - description: The body to create a Party
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/handler.UpdatePartyBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/datastruct.PublicParty'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Update a Party
      tags:
      - CRUD
  /near:
    get:
      description: Get a list of parties near a location
      parameters:
      - description: Latitude
        in: query
        name: lat
        required: true
        type: number
      - description: Longitude
        in: query
        name: long
        required: true
        type: number
      - description: Geohash precision
        in: query
        name: precision
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/datastruct.PublicParty'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Search by location
      tags:
      - GEO
swagger: "2.0"
