apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment
spec:
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      labels:
        app: comment
    spec:
      containers:
        - name: comment
          image: jonashiltl/comment-service
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: SCYLLA_KEYSPACE
              value: sessions
            - name: SCYLLA_HOSTS
              value: host.docker.internal
            - name: NATS_CLUSTER
              value: nats://host.docker.internal:4222
          ports:
            - containerPort: 8080
