apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-aggregator
spec:
  selector:
    matchLabels:
      app: data-aggregator
  template:
    metadata:
      labels:
        app: data-aggregator
    spec:
      containers:
        - name: data-aggregator
          image: jonashiltl/data-aggregator
          resources:
            limits:
              memory: "250Mi"
              cpu: "500m"
          command:
            - air
          ports:
            - containerPort: 8081
