apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: jonashiltl/notification-service
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: NATS_CLUSTER
              value: nats://host.docker.internal:4222
          ports:
            - containerPort: 8080
