apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
spec:
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
        - name: profile
          image: jonashiltl/profile-service
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          command:
            - sh -c "cd services/profile && air"
          ports:
            - containerPort: 8081
