apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: jonashiltl/user-service
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: MYSQL
              value: root:rootPassword@tcp(host.docker.internal:3306)/sessions?parseTime=true
            - name: NATS_CLUSTER
              value: nats://host.docker.internal:4222
          ports:
            - containerPort: 8080
