apiVersion: v1
kind: Pod
metadata:
  name: comment
  labels:
    name: comment
spec:
  containers:
    - name: comment
      image: jonashiltl/comment-service
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080

    - name: comment-sidecar
      image: jonashiltl/comment-service-sidecar
      lifecycle:
        type: Sidecar
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
