apiVersion: v1
kind: Pod
metadata:
  name: party
  labels:
    name: party
spec:
  containers:
    - name: party
      image: jonashiltl/party-service
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
        - name: SCYLLA_KEYSPACE
          value: sessions
        - name: SCYLLA_HOSTS
          value: host.docker.internal
        - name: NATS_CLUSTER
          value: nats://host.docker.internal:4222
      ports:
        - containerPort: 8080

    - name: party-sidecar
      image: jonashiltl/party-service-sidecar
      lifecycle:
        type: Sidecar
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
