apiVersion: v1
kind: Pod
metadata:
  name: profile
  labels:
    name: profile
spec:
  containers:
    - name: profile
      image: jonashiltl/profile-service
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"

    - name: profile-sidecar
      image: jonashiltl/profile-service-sidecar
      lifecycle:
        type: Sidecar
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
