apiVersion: v1
kind: Pod
metadata:
  name: user
  labels:
    name: user
spec:
  containers:
    - name: user
      image: jonashiltl/user-service
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
        - name: MONGO_URL
          value: mongodb://root:rootpassword@host.docker.internal:27017/
        - name: NATS_CLUSTER
          value: nats://host.docker.internal:4222
        - name: DO_ENDPOINT
          value: https://example.comn
        - name: DO_TOKEN
          value: gaww12t2tawdawgt12

    - name: user-sidecar
      image: jonashiltl/user-service-sidecar
      lifecycle:
        type: Sidecar
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
